# EmberTide (Reef) — tmux status bar & chrome theme
# tmux inherits its 16 ANSI colors from the underlying terminal emulator —
# pair this with one of the terminal themes in this repo. This file only
# themes tmux's own UI: status bar, pane borders, messages, copy mode.
#
# Source it from ~/.tmux.conf:
#   source-file ~/.config/tmux/embertide.tmux
# Generated by scripts/build.py — do not hand-edit.

set -g status-style "bg=#001219,fg=#e9d8a6"
set -g status-left "#[bg=#ee9b00,fg=#001219,bold] #S #[bg=#001219,fg=#ee9b00]"
set -g status-right "#[fg=#008388]%Y-%m-%d #[fg=#e9d8a6]%H:%M "
set -g window-status-current-style "bg=#005f73,fg=#e9d8a6,bold"
set -g window-status-style "bg=#001219,fg=#384f57"

set -g pane-border-style "fg=#005f73"
set -g pane-active-border-style "fg=#ee9b00"

set -g message-style "bg=#005f73,fg=#e9d8a6"
set -g message-command-style "bg=#005f73,fg=#e9d8a6"

set -g mode-style "bg=#005f73,fg=#e9d8a6"
